### PR TITLE
Test skipping

### PR DESCRIPTION
**Pull request by hugovk**
Testing if the skipper tag works in AzP

https://developercommunity.visualstudio.com/idea/420289/add-support-ci-skip-and-azure-skip-to-azure-pipeli.html

### CODE REVIEW

**Comment by hugovk** [comment]
I wonder why skipping works here but not in https://github.com/python-pillow/Pillow/pull/3805?

**Comment by mloskot** [comment]
@hugovk I removed `trigger: master` filter https://github.com/mloskot/ci-test/commit/8091b1cfd314e4356f4cf403c99e1c799a97fe77 and rebased all my test PRs. AFAICT, the builds seem to be skipped as expected.

**Comment by mloskot** [comment]
@hugovk No, something is not right!
AzP builds are not triggered at all, even for the `master` commit https://github.com/mloskot/ci-test/commit/8091b1cfd314e4356f4cf403c99e1c799a97fe77
https://dev.azure.com/mloskot/ci-test/_build?definitionId=3

This one also should build AzP https://github.com/mloskot/ci-test/pull/5

Something is broken here. This seems to be repo-specific issue, as I'm not seeing such problems in 
https://dev.azure.com/mloskot/gil/_build?definitionId=6 for https://github.com/mloskot/gil/
or
https://dev.azure.com/boostorg/gil/_build?definitionId=4 for the upstream at https://github.com/boostorg/gil

**Comment by hugovk** [comment]
Yes, also confirmed in https://github.com/mloskot/ci-test/pull/6!

I think it might be because your file is `.azure-pipelines.yml` with a dot, and AzP only detect without a dot unless you manually set it up somewhere in the interface?

https://github.com/python-pillow/Pillow/pull/3805 has `azure-pipelines.yml` with no dot.

**Comment by mloskot** [comment]
> I think it might be because your file is .azure-pipelines.yml with a dot, and AzP only detect without a dot unless you manually set it up somewhere in the interface?

The name should not cause any issues. You can select a file with arbitrary name via Import Pipeline on dev.azure.com. Anyhow, I have used `.azure-pipelines.yml` with numerous projects and w/o issues.

------

I have removed the `ci-test` project from Azure and recreated it, then re-added the pipeline.
Then, updated this PR https://github.com/mloskot/ci-test/pull/5 and it's building now.

**Pull request closed without merging**
